name: author assigned check

on: [pull_request]

jobs:
  assign-author:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.1

  build-and-run-tests:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: ./gradlew clean test
        uses: actions/create-github-app-token@v1.11.3