name: Spotless Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  spotless-check:
    name: Run Spotless Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck